language: php

php:
  - 7.0

sudo: false

cache:
  directories:
    - vendor

branches:
  only:
    - master

install:
  - composer install --no-dev

script:
  - phpunit -c phpunit.xml.dist --coverage-clover build/logs/clover.xml